### ISSUE TITLE
I get a redirect loop when i tried to use this plugin

### ISSUE THREAD

**Issue by DanielUche** [AlessandroMinoccheri/UserPermissions#3]

**Comment by AlessandroMinoccheri** [comment]
Can you please let me know which version are you using of cakephp?
Can you please show your code to use the plugin?

Thanks

**Comment by DanielUche** [comment]
$user_types = $this->Roles->getRoles();
$rules = array(
    'user_type' => $user_type['name'],
    'redirect' => '/schools/',
    'message' => 'You do not have permission to access this page',
    'action' =>  $this->params['action'],
    'controller' =>  $this->params['controller'],
    'groups' => array(
        'guest' => array('register', 'logout', 'login'),
        'admin' => array('*'), 
        'teacher' => array('register', 'add', 'logout', 'index', 'edit'),
        'user' => array('register', 'add', 'logout', 'index')
    ),
    'views' => array(
        'edit' => 'checkEdit',
        'delete' => 'checkDelete',
    ),
);

$this->UserPermissions->allow($rules);

I do this in schools controller.

Pls note; if i change the redirect parameter to a different controller it redirects successfully. But i cant access non of the actions in the school controller.

**Comment by DanielUche** [comment]
I will appreciate any assistance from you to get this working. Since i prefer you plugin to tinyAuth because of its simplicity of use

**Comment by AlessandroMinoccheri** [comment]
Which version of cakephp are you using? cakephp 2.x or cakephp 3.x?

**Comment by DanielUche** [comment]
Cakephp 3x

**Comment by DanielUche** [comment]
3.0.3 to be precise

**Comment by AlessandroMinoccheri** [comment]
Ok, when you get the loop are you a guest? an admin user? a logged in user?

**Comment by DanielUche** [comment]
I think as a guest since i cant even login to my admin account

**Comment by AlessandroMinoccheri** [comment]
So if you a guest you redirect to: /schools/ so It's like to redirect to: /schools/index
In your array guest are only able to view:
array('register', 'logout', 'login'),

Not index page

**Comment by DanielUche** [comment]
I tried redirecting to /schools/login/ but still get the same problem

**Comment by AlessandroMinoccheri** [comment]
Try to view what is $user_types

**Comment by DanielUche** [comment]
it returns teacher

**Comment by DanielUche** [comment]
or schools

**Comment by DanielUche** [comment]
And if am not logged in it returns guest

**Comment by AlessandroMinoccheri** [comment]
try please to change this:
'guest' => array('register', 'logout', 'login'),

to this:

'guest' => array('register', 'logout', 'login', 'index'),

and let me know

**Comment by DanielUche** [comment]
Ok sir, but login is the view i want a user redirected to after sucessfull login

**Comment by DanielUche** [comment]
I will like to know Why i cant even access the login view for schools controller it keeps redirecting me

**Comment by AlessandroMinoccheri** [comment]
ok your purpose is:
- login is visible to all
- after login redirect to... another page
right?

P.S.parameter redirect it will be used when the user can't access to a page, when he doesn't have permission go to the redirect link

**Comment by DanielUche** [comment]
Ok

**Comment by DanielUche** [comment]
I still get the message "This webpage has a redirect loop"

**Comment by DanielUche** [comment]
But when i redirect to a different controller it works just that i cant access any action from my schools controller

**Comment by AlessandroMinoccheri** [comment]
Ok I need to check this evening this problem.
I think that tomorrow I can write to you a solution or correct the bug

**Comment by DanielUche** [comment]
Ok, thanks

**Comment by AlessandroMinoccheri** [comment]
I have fixed the problem.
Try now to get new version of the plugin and let me know if it works!
